title: Bipolar
description: A frontend & backend blog written by a pair of twin developers.

paginate: 5
paginate_path: /page/:num/

kramdown:
  syntax_highlighter_opts:
    disable: true

gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

baseurl: ""
url: http://twin.github.io
github:
  url: http://twin.github.io

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:title/
  - scope:
      path: ""
      type: drafts
    values:
      layout: post


logo: /images/logo.png

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .sass-cache
  - vendor
